spring:
  #数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shiro?serverTimezone=Asia/Shanghai
    username: root
    password: Aimer
    driver-class-name: com.mysql.cj.jdbc.Driver

  # freemarker 渲染 Web 视图
  freemarker:
    suffix: .ftl
    template-loader-path: classpath:/templates
    request-context-attribute: request

  mvc:
    # put delete
    hiddenmethod:
      filter:
        enabled: true
    static-path-pattern: /static/**

  servlet:
    multipart:
      #设置单个文件大小
      max-file-size: 50MB
      #设置单次请求文件的总大小
      max-request-size: 50MB

# 扫描mapper.xml
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml

# 把日志打印到控制台
logging:
  level:
    com.yr.dao: DEBUG

#shiro:
#  loginUrl: /login
#  successUrl: /index
#  unauthorizedUrl: /unauthorizedm
